name: Paulie Grid Test
favicon: null
layout_spectrum: 0.536892278585583
typography_spectrum: 0.6079312320798635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c09554'
    - '#ffffff'
    - '#4f7e14'
    - '#28f62d'
    - '#b8dd6f'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
