name: Paulie Grid Test
favicon: null
layout_spectrum: 0.536892278585583
typography_spectrum: 0.6079312320798635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.36467043007723987
  lightness: 0.4851737762801349
  saturation: 0.9864027795847505
  rhythmicContrast: 0.8379684942774475
purpose: []
